### PR TITLE
Bugfix and Sync of node deletion

### PR DESCRIPTION
**Pull request by Treholt3103**
This should fix a lot of the bugs when building roads/waterpipes/powerlines, and make the sync faster.

This also adds the functionality of
syncing deleting roads ect. it takes a few secounds before deleted roads are removed on the recieving Client/Server

### CODE REVIEW

**Comment by DominicMaas** [comment]
I don't have time to check everything out, but I assume it all works!

**Comment by MisterX2000** [comment]
Deleting roads works now, but I've noticed another problem.
When you place roads too fast only parts of them will sync.

**Comment by Treholt3103** [comment]
I will check it out :)

**Comment by Treholt3103** [comment]
The bug seems to be caused by some no longer necessary thread.sleeping, i have just uploaded a fix that seems to solve the bug :)

**Pull request merged**
