### PR TITLE
Implement NAT hole punching and make API server configurable

### PR DESCRIPTION
**Pull request by kaenganxt**
When joining a server, the implementation will now
1. Request the hole punching server to initiate the NAT hole punching
2. The hole punching server returns a registered ip address and instructs the CSM server to punch a hole
3. LiteNetLib performs the hole punching and tries to verify a working connection
4. Our implementation tries to use the returned IP address to connect to the CSM server
5. If unsuccessful or server is not known on the hole punching server, the given IP address is used to connect directly (e.g. for a local network or Hamachi)

The hole punching server was improved slightly, and is now included in this repository.

The server is currently running on api.citiesskylinesmultiplayer.com port 4240 (only IPv4 for now).

An additional feature introduced with this patch is the ability to change the API server through a mod setting (if someone wants to host their own setup).

### CODE REVIEW

**Comment by DominicMaas** [comment]
Code wise (visually), it looks good, will test it out over the weekend.

**Comment by kaenganxt** [comment]
I finally had the time to include the port checking mechanism. For this, I refactored most of the CSM <-> GlobalServer communication and included the GS project into this repository. It is not included in the solution as this didn't work for me with Mono (Because the GS is .NET core).

Port checking works by simulating a CSM client on the GS and performing the same procedure as with the regular connection procedure.
I also created a Docker Registry for the GS image at https://github.com/orgs/CitiesSkylinesMultiplayer/packages/container/package/apiserver

Maybe I'll add the building of this Docker Image to the Github Action later today.
Please take a look again @DominicMaas :)

**Comment by DominicMaas** [comment]
ooooh nice! I've got some free time at the moment so I'll check this out

**Comment by DominicMaas** [comment]
hmmm, I'm unable to load the CSM project in Visual Studio:

image

**Comment by kaenganxt** [comment]
> hmmm, I'm unable to load the CSM project in Visual Studio:

The Data folder should be a symlink to the GS project's Data folder (so the packets are the same). Could this be a problem with Visual Studio? Does it look correct in the file system? I personally use Jetbrains Rider as an IDE where it works fine.

**Comment by DominicMaas** [comment]
image

Do symlink's work through git? Ooh, are you developing on Linux?

**Comment by DominicMaas** [comment]
I could probably get away with replacing paths to the data folder with relative paths in the csproj file, looks like there are issues with using linux symlinks on Windows (there are local ways to get around this, but would complicate PRs in the future for people wanting to contribute)

**Comment by kaenganxt** [comment]
> Do symlink's work through git? Ooh, are you developing on Linux?

Yes, I'm on Linux. In theory, symlinks should work on Windows. I just found this post: https://stackoverflow.com/a/59761201

If relative paths work properly, we can also use those. I just wanted to avoid duplicate code especially for the protocols.

**Comment by DominicMaas** [comment]
I see, I'll give relative paths a try for now. I'd eventually like to try modernizing our c# csprojs and still build for .net 3.5 (which should be possible, but will need to see if mono freaks out, and if everything still works. Future PR though)

**Comment by DominicMaas** [comment]
Hopefully this has not broken the CI or Linux builds

**Comment by kaenganxt** [comment]
Looks good for me on Linux

**Review by DominicMaas — APPROVED** [review]

**Pull request merged**
