### PR TITLE
[Feature] Player Pointers & Color Picker

### PR DESCRIPTION
**Pull request by dfrankes**
This PR adds 2 new features to CSM:

**Player Pointers**
The pointer will allow everyone to see everyone elses their camera position and rotation
[Preview .gif](https://dfrankes.nl/2019-10-20_22-11-03.gif)

**Player color picker in Join Game menu**
this allows you to set your own color for when connecting to a server, this color will also be your pointer color.
[Preview image](https://i.imgur.com/4uclzY9.jpg)

**UnityEngine.Color serialization**
Added to so you can  broadcast your color to other clients

Closed PR #135 because i changed quite a bit.

### CODE REVIEW

**Comment by DominicMaas** [comment]
I'll wait until https://github.com/DominicMaas/Tango/pull/133 is merged into master before merging this.

**Comment by DominicMaas** [comment]
Looks like a few slight changes need to be made after rebasing onto master again. Just in `ICameraHandler.cs` I think.

**Comment by dfrankes** [comment]
@DominicMaas Changed the Harmony import to HarmonyLib

**Review by DominicMaas — APPROVED** [review]

**Comment by DominicMaas** [comment]
Thanks :)

**Pull request merged**
