### PR TITLE
Small bug fix, making Roadbuilding instant

### PR DESCRIPTION
**Pull request by Treholt3103**
Seems that with the last bugfix it was no longer necessary to sleep the thread.

Sleeping is now removed creating an nearly instant sync of road creation, and fixing the bug where roads would not be created if they were created at a very high speed

### CODE REVIEW

**Comment by DominicMaas** [comment]
There appears to be two files changed `NodeAndSegmentExtension.cs`, and `NodeandSegmentExtension.cs` with the same changes, a GitHub bug maybe?

**Comment by DominicMaas** [comment]
Oh, both files are in the source code, probably delete `NodeandSegmentExtension.cs` making sure they are the same.

**Comment by DominicMaas** [comment]
I'll fix it up after merge.

**Comment by DominicMaas** [comment]
Build is failing because `NetSegmentLocked` does not exist on `NodeAndSegmentExtension`.

```
2018-11-07T17:29:38.5017403Z   Commands\Handler\NodeCreateHandler.cs(16,48): error CS0117: 'NodeAndSegmentExtension' does not contain a definition for 'NetSegmentLocked' [D:\a\1\s\src\CSM.csproj]
2018-11-07T17:29:38.5017814Z   Commands\Handler\NodeCreateHandler.cs(44,48): error CS0117: 'NodeAndSegmentExtension' does not contain a definition for 'NetSegmentLocked' [D:\a\1\s\src\CSM.csproj]
2018-11-07T17:29:38.5017971Z   Commands\Handler\NodeSegmentCreateHandler.cs(16,48): error CS0117: 'NodeAndSegmentExtension' does not contain a definition for 'NetSegmentLocked' [D:\a\1\s\src\CSM.csproj]
2018-11-07T17:29:38.5018103Z   Commands\Handler\NodeSegmentCreateHandler.cs(29,48): error CS0117: 'NodeAndSegmentExtension' does not contain a definition for 'NetSegmentLocked' [D:\a\1\s\src\CSM.csproj]
```

**Comment by Treholt3103** [comment]
Ohh fuck me for being lazy and just uploading the small change from a working document, instead of uploading it all, can you just remove those four lines of code, :/

**Comment by DominicMaas** [comment]
No worries, and just did!

**Pull request merged**
