### PR TITLE
Quaternion Serialization

### PR DESCRIPTION
**Pull request by dfrankes**
Added Quaternion Serialization for an upcomming feature: multiplayer cursor.

### CODE REVIEW

**Review by kaenganxt — CHANGES_REQUESTED** [review]
Thanks for contributing to the project!
It looks like you forgot to add the changes in the CSM.csproj file, so QuaternionSurrogate.cs is not added for compilation (The build fails).
Please add this change to the pull request. Apart from that, the patch looks good! :)

**Comment by dfrankes** [comment]
@kaenganxt Added CSM.csproj

**Review by kaenganxt — APPROVED** [review]
Thank you!

**Comment by DominicMaas** [comment]
Thanks!

**Pull request merged**
