### PR TITLE
Improved command handling (Implements #24)

### PR DESCRIPTION
**Pull request by kaenganxt**
This pull request improves the command handling using an object oriented approach.

There's now a handler class for every command with two methods for handling the command on the client and server side.

The handler base class also has two virtual methods which are called on client connect and disconnect (on the server). They are used to update handler specific data, for example to send initial updates (like the current game state) to a new client.

To send commands, the id is no longer needed. There several send methods in the Command class. Example: `Command.SendToServer(new ConnectionCloseCommand());`

### CODE REVIEW

**Comment by DominicMaas** [comment]
Awesome! I assume that everything still works as before? Building syncing, play pause, simulation speed etc.?

**Comment by kaenganxt** [comment]
I didn't test everything, but play/pause and simulation speed did work, so I expect that the rest works, too.

**Comment by DominicMaas** [comment]
Alright, I'll merge the changes and start performing some testing.

**Comment by DominicMaas** [comment]
Everything is looking good, thanks a lot!

**Pull request merged**
