### PR TITLE
Update for Plazas and Promenades

### LINKED ISSUE #279: Sync stopped working with new Game version
At least all streets dont get synced anymore since the new version were introduced on 14.09.2022 where some new streets .

**To Reproduce**
1. just update the game
2. test the sync

**Active DLCs**
none

**Active mods**
none

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 2201.180.0.0
- Game version: 1.15.0-f5

### PR DESCRIPTION
**Pull request by kaenganxt**
- Some radio stations were moved to different bitmap
- Change ApplyBrush method parameters

Fixes #279

### CODE REVIEW

**Comment by DominicMaas** [comment]
Looks good to me from a code side!

Do we want to update the GitHub release notes now (and in game release notes) for a release later today?

**Review by DominicMaas — APPROVED** [review]

**Comment by kaenganxt** [comment]
> Do we want to update the GitHub release notes now (and in game release notes) for a release later today?

Yes, I can add the in-game release notes to this pull request.

**Comment by DominicMaas** [comment]
And a reminder to myself, I'm pretty sure this upcoming release contains the new harmony changes right? Will need to add a steam dependency, and make sure the instructions are updated for non-steam users (and maybe a FAQ / Common Issues listing)

**Comment by kaenganxt** [comment]
Yup, I think the Harmony API also shows in-game popups for non-Steam players on where to download Harmony, so this should already be a first step for help.

**Comment by DominicMaas** [comment]
Sounds good, feel free to do a GitHub release with the CI build in main, I'll do a steam release in about 12ish hours (unless you want to wait to align with steam release).

**Comment by kaenganxt** [comment]
I created a draft release which should be ready for release. You can publish this draft release once you do the Steam release.

**Comment by DominicMaas** [comment]
Thanks!

**Pull request merged**
