### PR TITLE
Adds the functionality of syncing zones

### PR DESCRIPTION
**Pull request by Treholt3103**
This adds the functionality of syncing zones (both adding and removal)
Compared to syncing Node and Segment this is trivial and it should not give us to many problems.

Also something went wrong with github :/

### CODE REVIEW

**Comment by DominicMaas** [comment]
You will have to manually delete `src/Extensions/NodeandSegmentExtension.cs`. Windows kinda thinks they are the same file (because case insensitive). 

It might fix GitHub.

**Comment by Treholt3103** [comment]
Danm, okay i will take a backup, sync it and reapply my changes :)

**Comment by Treholt3103** [comment]
okay its reuploaded, now it says no conflict?

**Comment by DominicMaas** [comment]
It's complaining about the `NodeAndSegmentExtension` file. Line numbers are in the error messages (13,1) etc.

```
2018-11-07T19:18:09.3650216Z   Extensions\NodeAndSegmentExtension.cs(13,1): error CS8300: Merge conflict marker encountered [D:\a\1\s\src\CSM.csproj]
2018-11-07T19:18:09.3650705Z   Extensions\NodeAndSegmentExtension.cs(164,1): error CS8300: Merge conflict marker encountered [D:\a\1\s\src\CSM.csproj]
2018-11-07T19:18:09.3651018Z   Extensions\NodeAndSegmentExtension.cs(283,1): error CS8300: Merge conflict marker encountered [D:\a\1\s\src\CSM.csproj]
2018-11-07T19:18:09.3651116Z   Extensions\NodeAndSegmentExtension.cs(298,1): error CS8300: Merge conflict marker encountered [D:\a\1\s\src\CSM.csproj]
2018-11-07T19:18:09.3651188Z   Extensions\NodeAndSegmentExtension.cs(457,1): error CS8300: Merge conflict marker encountered [D:\a\1\s\src\CSM.csproj]
2018-11-07T19:18:09.3651259Z   Extensions\NodeAndSegmentExtension.cs(596,1): error CS8300: Merge conflict marker encountered [D:\a\1\s\src\CSM.csproj]
```

**Pull request closed without merging**
