### PR TITLE
Rewrite net/building sync

### LINKED ISSUE #95: It's not possible to extend a waterpipe another player created
**Describe the bug**
It's not possible to extend a waterpipe another player created.
You need to extend it somewhere in between.

### LINKED ISSUE #99: Toll booths/Relocate building
**Describe the bug**
When moving toll booths it leaves the road behind making an infinite road that you cannot move. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a toll road
2. Relocate building
3. Place down at another position
4. The roads would not have been removed and it will leave an infinite road 

**Expected behaviour**
Will not leave behind a road

### LINKED ISSUE #121: Bridge pillars don't have the correct height and similar problems
Since bridge pillars are buildings, it seems that updates to the building's configuration are missing and need to be synced.

An approach to solve this problem can be found in #107 

Related issues:
- Power poles can be clicked at by other players

### PR DESCRIPTION
**Pull request by kaenganxt**
This pull request changes how nodes, segments and buildings are synced.

Instead of syncing all created objects at the manager level (NetManager, BuildingManager), this now tracks all important calls on the tool level (NetTool, BuildingTool). This makes sure that all settings for the created buildings, nodes and segments, that are applied after the manager methods have finished, are synced correctly. This change should make it easier for the transport line syncing, too.

The commit:
- Fixes #121 
- Fixes #99 
- Fixes #95
- and maybe other problems

Because there was an issue with Harmony with patching a certain method, I fixed it there (https://github.com/pardeike/Harmony/pull/211). But this means that we need to use the newest version Harmony 2 which is not released yet.

I set up a small Azure pipeline to build the artifacts: https://dev.azure.com/kaenganxt/Harmony/_build?definitionId=1
@DominicMaas: You can download the artifact from there to fix our CI build. (The dll is taken from the assemblies folder for now)
I'll look into a way to improve this (maybe I'll set up a small nuget repo as long as the new Harmony version is not released yet)

### CODE REVIEW

**Comment by DominicMaas** [comment]
Thanks, I'll take a look at this when I'm home this afternoon!

**Comment by kaenganxt** [comment]
I'm currently building on my fork of Harmony so I could add an azure config file (https://github.com/kaenganxt/Harmony/blob/master/azure-pipelines.yml). I'm not sure if the current build settings are enough to be able to get the artifact correctly. Just tell me if you need any different settings.

**Comment by DominicMaas** [comment]
Sorry for the delay, I'll have to get back to you next week (studying for an exam on Monday)

**Comment by DominicMaas** [comment]
Another option is just to bundle the dll with the source code for now

**Comment by kaenganxt** [comment]
I'm also happy with that for now. I just added the dll and the build looks fine :)

**Review by DominicMaas — APPROVED** [review]

**Pull request merged**
